/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useTimer } from 'react-timer-hook'

type timerProps = {
  expiryTimestamp: any
}

function MyTimer({expiryTimestamp} : timerProps) {
  const {
    days,
    seconds,
    minutes,
    hours,
    
  } = useTimer({ expiryTimestamp, onExpire: () => console.warn('onExpire called') });

  return (

    <div id={styles.countdown_dashboard}>
    <div className={styles.dashp}>
      <p id={styles.days}>{days}</p>
      <span className={styles.dashtitle}>Dias</span>
    </div>
    <div className={styles.dashp}>
      <p id={styles.hours}>{hours}</p>
      <span className={styles.dashtitle}>Horas</span>
    </div>
    <div className={styles.dashp}>
      <p id={styles.minutes}>{minutes}</p>
      <span className={styles.dashtitle}>Minutos</span>
    </div>
    <div className={styles.dashp}>
      <p id={styles.seconds}>{seconds}</p>
      <span className={styles.dashtitle}>Segundos</span>
    </div>
  </div>
   
  );
}

const Home: NextPage = () => {
  const time = new Date("Ma 06, 2022 00:00:00");
 

  return (
    <div id={styles.wrapper}>
      <Head>
        <title>Encontro dos QGR's - Campinas & Região</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://static.wixstatic.com/media/1b7734_b5d5b897fcd24dc8b5316f929705589a~mv2.png/v1/fill/w_220,h_81,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/qgr2.png" />
        
      </Head>

      
      <header className={styles.header}>
        <figure>
        <Image width={220} height={80} src="https://static.wixstatic.com/media/1b7734_b5d5b897fcd24dc8b5316f929705589a~mv2.png/v1/fill/w_220,h_81,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/qgr2.png" className={styles.logo} alt="Encontro dos QGR'S de Campinas e região" />
        </figure>

        <h2 className={styles.date}>
          Sexta-feira, 06 de Maio ás 20h
        </h2>
        <h1>Encontro dos QGR 'S de Campinas e Região</h1>
        <MyTimer expiryTimestamp={time} />
      </header>
      <main className={styles.main}>
        <section id={styles.speaker}>

          <div className={styles.speaker}>
            <div className={styles.info}>
              <h2>Palestrante</h2>
              <h3>Júlio Rocha</h3>
              <p>CEO Resort Pablo Marçal</p>
            </div>

            <Image width={190} height={190} src="https://comunidadevinhedocampinas.com.br/img/julio-rocha.png" className={styles.avatar} alt="Júlio Rocha" />

          </div>
        </section>
        <section id={styles.praise}>
          <div className={styles.praise}>

          <Image width={190} height={190} src="https://comunidadevinhedocampinas.com.br/img/clebinho-santos.png" className={styles.avatar} alt="Clebinho Santos" />
            <div className={styles.info}>
              <h2>Múscica</h2>
              <h3>Clebinho Santos</h3>
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        <a className={styles.button} href="https://forms.gle/zXiu1dBnMCqiwoRi8">Confirmar presença</a>
      </footer>
    </div>

  )
}

export default Home
