/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'




const Home: NextPage = () => {
 
 
  return (
    <div id={styles.wrapper}>
      <Head>
        <title>Encontro dos QGR's - Campinas & Região</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://static.wixstatic.com/media/1b7734_b5d5b897fcd24dc8b5316f929705589a~mv2.png/v1/fill/w_220,h_81,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/qgr2.png" />
        
      </Head>

      
      <header className={styles.header}>
        <figure>
        <Image width={220} height={80} src="https://static.wixstatic.com/media/1b7734_b5d5b897fcd24dc8b5316f929705589a~mv2.png/v1/fill/w_220,h_81,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/qgr2.png" className={styles.logo} alt="Encontro dos QGR'S de Campinas e região" />
        </figure>

        <h2 className={styles.date}>
          Sexta-feira, 06 de Maio ás 20h
        </h2>
        <h1>Encontro dos QGR 'S de Campinas e Região</h1>
        <h1 className={styles.textGreen}>BORA TTT</h1>
      </header>
      <main className={styles.main}>
        <section id={styles.speaker}>

          <div className={styles.speaker}>
            <div className={styles.info}>
              <h2>Palestrante</h2>
              <h3>Júlio Rocha</h3>
              <p>CEO Resort Pablo Marçal</p>
            </div>

            <Image width={190} height={190} src="https://comunidadevinhedocampinas.com.br/img/julio-rocha.png" className={styles.avatar} alt="Júlio Rocha" />

          </div>
        </section>
        <section id={styles.praise}>
          <div className={styles.praise}>

          <Image width={190} height={190} src="https://comunidadevinhedocampinas.com.br/img/clebinho-santos.png" className={styles.avatar} alt="Clebinho Santos" />
            <div className={styles.info}>
              <h2>Música</h2>
              <h3>Clebinho Santos</h3>
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        <a className={styles.button} href="https://forms.gle/zXiu1dBnMCqiwoRi8">Confirmar presença</a>
      </footer>
    </div>

  )
}

export default Home
